title: <span class="name">The Garden Project</span>
theme: minima
collections:
  designs:
    output: true


header_pages: 
  - shop.md
  - cart.md
  - about.md


defaults:
  - scope:
      type: "designs"
    values:
      layout: design
