title: The Garden Project
theme: minima
collections:
  designs:
    output: true

header-pages:
-shop.md
-cart.md
-about.md


defaults:
  - scope:
      type: "designs"
    values:
      layout: design
