title: The Garden Project
theme: minima
logo: ./assets/logov1.png
collections:
  designs:
    output: true


header_pages: 
  - shop.md
  - cart.md
  - about.md


defaults:
  - scope:
      type: "designs"
    values:
      layout: design
